# meta
# seed is handled by the spawner
# uuid is handled by the spawner (and otherwise one is created later)

# resources
cuda: true
fp16: true

# logging
wandb_project: 'psyduck'

# dataset
dataset_handle: 'bigearthnet'
# data path is handled by the spawner w/ an environ variable
val_split: 0.25
test_split: 0.25

# training
epochs: 100
batch_size: 128
save_freq: 1
eval_every: 100

# opt
lr: 1e-4
wd: 0.
clip_norm: 0
acc_grad_steps: 8
lars: true
sched: true

# algo
algo_handle: 'compressor'

# opt 2
max_lr: 1e-3

# model architecture
in_channels: 3
z_channels: 32
ae_hidden: 128
ae_resblocks: 2
ae_kernel: 4
dsf: 8

# loss
alpha: 1.
beta: 1.

# centers
c_num: 8
c_min: -2.
c_max: 2.
